-- MySQL Script generated by MySQL Workbench
-- Fri Oct  9 17:37:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema curso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema curso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `curso` DEFAULT CHARACTER SET utf8 ;
USE `curso` ;

-- -----------------------------------------------------
-- Table `curso`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso`.`User` ;

CREATE TABLE IF NOT EXISTS `curso`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `password` VARCHAR(255) NOT NULL,
  `softdelete` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso`.`productos` ;

CREATE TABLE IF NOT EXISTS `curso`.`productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `softdelete` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idproductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso`.`pedido` ;

CREATE TABLE IF NOT EXISTS `curso`.`pedido` (
  `idpedido` INT NOT NULL,
  `fecha` TIMESTAMP NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_User_idx` (`User_idUser`),
  CONSTRAINT `fk_pedido_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `curso`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso`.`pedido_has_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso`.`pedido_has_productos` ;

CREATE TABLE IF NOT EXISTS `curso`.`pedido_has_productos` (
  `pedido_idpedido` INT NOT NULL,
  `productos_idproductos` INT NOT NULL,
  PRIMARY KEY (`pedido_idpedido`, `productos_idproductos`),
  INDEX `fk_pedido_has_productos_productos1_idx` (`productos_idproductos`),
  INDEX `fk_pedido_has_productos_pedido1_idx` (`pedido_idpedido`),
  CONSTRAINT `fk_pedido_has_productos_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `curso`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_productos_productos1`
    FOREIGN KEY (`productos_idproductos`)
    REFERENCES `curso`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
